package generator;

public enum Tokens {
	ASSIGN, CLASS, COMMA, DIGIT, ELSE, ENDCLASS, ENDELSE, ENDFUNCTION, ENDIF, EQUALS, FUNCTION, ID, IF, LPAREN,
	MINUS, PLUS, RPAREN, SLASH, STAR, VALUE, VAR, VARIABLE, WS
}
