package generator;

public enum Tokens {
	ASSIGN, CLASS, COMMA, DECREASE, DIGIT, ELSE, ENDCLASS, ENDELSE, ENDFOR, ENDFUNCTION, ENDIF, ENDWHILE, EQUALS, FOR, FUNCTION,
	GT, GTE, ID, IF, INCREASE,LPAREN, LT, LTE, MINUS, PLUS, RETURN, RPAREN, SEMICOLON, SLASH, STAR, VALUE, VAR, VARIABLE, WHILE, WS
}
