package generator;

public enum Tokens {
    ARR, ASSIGN, CLASS, COMMA, DECREASE, DIGIT, ELSE, ENDCLASS, ENDELSE, ENDFOR, ENDFUNCTION, ENDIF, ENDWHILE, EQUALS, FOR, FUNCTION,
	GT, GTE, ID, IF, INCREASE, LBRACK, LPAREN, LT, LTE, MINUS, PLUS, QUESTIONS, RBRACK, RETURN, RPAREN, SEMICOLON, SLASH, STAR, VALUE, VAR, VARIABLE, WHILE, WS
}
